################################################################################
## 2016 Magnet Up configuration
################################################################################
#
datasets:
  Lamarr:
    files:
      - /pclhcb06/landerli/TrackingParametrization/data/GaussTupleForLucio.root
       
  BrunelRecoed:
    files:
      #     - /pclhcb06/landerli/TrackingParametrization/data/trackRes_10000000_2016_MagUp.root
      - /pclhcb06/landerli/TrackingParametrization/data/unmerged/52/*/trackRes_10000000_2016_MagUp.root
      
           
  BrunelGenerated:
    files:
      - /pclhcb06/landerli/TrackingParametrization/data/unmerged/52/*/trackRes_10000000_2016_MagUp.root

