################################################################################
## Acceptance BDT 
################################################################################
acceptanceBDT:

  validationHistogramsPBins:
    Eta:
      variable: eta_ClosestToBeam
      binning: [150,0.5,8]
      xtitle: "Pseudorapidity"
      options: [] 

  validationHistogramsEtaBins:
    Momentum:
      variable: log(0.001+abs(pz)/1e3)/log(10)
      binning: [100,-2,8]
      xtitle: "$\\log_{10} (p_z/1 GeV)$"
      options: [] 

  validationHistogramsPEtaBins:
    #    Momentum:
    #      variable: log(pz/1e3)/log(10)
    #      binning: [100, -2, 2] 
    #      xtitle: "Longitudinal momentum [GeV/c]"
    #      options: 
    #        - logy 
    #          #- density

    Rho:
      variable: (x_ClosestToBeam**2 + y_ClosestToBeam**2)**0.5
      binning: [100, 0, 1.5]
      xtitle: "$\\rho$ @ClosestToBeam [mm]"
      options: [] 

    Atan2:
      variable: arctan2(x_ClosestToBeam, y_ClosestToBeam)
      binning: [100, -3.2, 3.2]
      xtitle: "$\\phi$ @ClosestToBeam"
      options: [] 

    RhoEndVelo:
      variable: (x_EndVelo**2 + y_EndVelo**2)**0.5
      binning: [100, 0, 400]
      xtitle: "$\\rho$ @EndVelo [mm]"
      options: [] 

    Atan2EndVelo:
      variable: arctan2(x_EndVelo, y_EndVelo)
      binning: [100, -3.2, 3.2]
      xtitle: "$\\phi$ @EndVelo"
      options: [] 


################################################################################
## Efficiency BDT 
################################################################################
efficiencyBDT:

  validationHistogramsPBins:
    Eta:
      variable: eta_ClosestToBeam
      binning: [150,0.5,8]
      xtitle: "Pseudorapidity"
      options: [] 

  validationHistogramsEtaBins:
    Momentum:
      variable: log(0.001+abs(pz)/1e3)/log(10)
      binning: [100,-2,8]
      xtitle: "$\\log_{10} (p_z/1 GeV)$"
      options: [] 

  validationHistogramsPEtaBins:
    #    Momentum:
    #      variable: log(pz/1e3)/log(10)
    #      binning: [100, -2, 2] 
    #      xtitle: "Longitudinal momentum [GeV/c]"
    #      options: 
    #        - logy 
    #          #- density

    Rho:
      variable: (x_ClosestToBeam**2 + y_ClosestToBeam**2)**0.5
      binning: [100, 0, 1.5]
      xtitle: "$\\rho$ @ClosestToBeam [mm]"
      options: [] 

    Atan2:
      variable: arctan2(x_ClosestToBeam, y_ClosestToBeam)
      binning: [100, -3.2, 3.2]
      xtitle: "$\\phi$ @ClosestToBeam"
      options: [] 

    RhoEndVelo:
      variable: (x_EndVelo**2 + y_EndVelo**2)**0.5
      binning: [100, 0, 400]
      xtitle: "$\\rho$ @EndVelo [mm]"
      options: [] 

    Atan2EndVelo:
      variable: arctan2(x_EndVelo, y_EndVelo)
      binning: [100, -3.2, 3.2]
      xtitle: "$\\phi$ @EndVelo"
      options: [] 


